library(igraph)
trade_data <- read.csv("trade_matrix.csv", row.names = 1)
trade_matrix <- as.matrix(trade_data)
trade_graph <- graph_from_adjacency_matrix(trade_matrix, mode = "directed")
average_path_length <- average.path.length(trade_graph)
write.csv(data.frame(average_path_length), file = "Average path length.csv", row.names = FALSE)